build.sbt
This PR adds the Sonatype default credential settings.
=> Credential Settings - Sonatype

build.sbt
Thanks @fedefernandez for catching the missing `io` :D
=> Fixes Organization and GroupId settings

README.md, build.sbt, project/plugins.sbt
And also, set up library versions locally in the `build.sbt` file.
=> Downgrades sbt-org-policies

build.sbt, src/main/scala/higherkindness/compendium/CompendiumServerStream.scala, src/main/scala/higherkindness/compendium/Main.scala, src/main/scala/higherkindness/compendium/http/RootService.scala, src/test/scala/higherkindness/compendium/http/RootServiceSpec.scala
Bump the versions of:
- **Circe**: `0.11.0` -> `0.11.1` Fixes #25, Fixes #24 
- **PureConfig**: `0.9.0` -> `0.10.1` Fixes #14
- **Http4s**: `0.18.21` -> `0.19.0` Fixes #15 Fixes #16 Fixes #17
=> Bump versions of circe, http4s and pureconfig

build.sbt, src/main/scala/higherkindness/compendium/CompendiumServerStream.scala, src/main/scala/higherkindness/compendium/Main.scala, src/main/scala/higherkindness/compendium/core/CompendiumService.scala, src/main/scala/higherkindness/compendium/core/ProtocolUtils.scala, src/main/scala/higherkindness/compendium/http/RootService.scala, src/test/scala/higherkindness/compendium/core/CompendiumServiceSpec.scala, src/test/scala/higherkindness/compendium/core/ProtocolUtilsSpec.scala, src/test/scala/higherkindness/compendium/http/RootServiceSpec.scala
Fixes #21 
We create an algebra with all the non-http logic from the endpoints.
=> Refactor code, creating an algebra with non-http logic

modules/server/src/main/scala/higherkindness/compendium/core/ProtocolUtils.scala, modules/server/src/test/scala/higherkindness/compendium/core/ProtocolUtilsSpec.scala
=> Reset internal state of avro parser

build.sbt
=> Bump version for PureConfig from 0.10.1 to 0.10.2

modules/client/src/main/scala/higherkindness/compendium/CompendiumClient.scala, modules/client/src/test/scala/higherkindness/compendium/CompendiumClientSpec.scala, modules/server/src/main/scala/higherkindness/compendium/Main.scala, modules/server/src/main/scala/higherkindness/compendium/core/CompendiumService.scala, modules/server/src/main/scala/higherkindness/compendium/core/ProtocolUtils.scala, modules/server/src/main/scala/higherkindness/compendium/db/DBService.scala, modules/server/src/main/scala/higherkindness/compendium/db/FileDBService.scala, modules/server/src/main/scala/higherkindness/compendium/http/RootService.scala, modules/server/src/main/scala/higherkindness/compendium/storage/FileStorage.scala, modules/server/src/main/scala/higherkindness/compendium/storage/Storage.scala, modules/server/src/test/scala/higherkindness/compendium/CompendiumArbitrary.scala, modules/server/src/test/scala/higherkindness/compendium/core/CompendiumServiceSpec.scala, modules/server/src/test/scala/higherkindness/compendium/core/CompendiumServiceStub.scala, modules/server/src/test/scala/higherkindness/compendium/core/ProtocolUtilsSpec.scala, modules/server/src/test/scala/higherkindness/compendium/core/ProtocolUtilsStub.scala, modules/server/src/test/scala/higherkindness/compendium/db/DBServiceStub.scala, modules/server/src/test/scala/higherkindness/compendium/db/FileDBServiceSpec.scala, modules/server/src/test/scala/higherkindness/compendium/http/RootServiceSpec.scala, modules/server/src/test/scala/higherkindness/compendium/models.scala, modules/server/src/test/scala/higherkindness/compendium/storage/FileStorageSpec.scala, modules/server/src/test/scala/higherkindness/compendium/storage/StorageStub.scala
This PR fixes the following issues:
- Compendium returns `Created` the first time a protocol is stored.
- Compendium returns `Ok` after a protocol is stored.
- Also hammock needs `http` in the route.
=> Compendium should returns Created the first time a protocol is uploaded

modules/client/src/main/scala/higherkindness/compendium/CompendiumClient.scala, modules/client/src/main/scala/higherkindness/compendium/Test.scala, modules/client/src/test/scala/higherkindness/compendium/CompendiumClientSpec.scala
We can't use `F[_]` or `IO` in `compendium-sbt`.
=> Remove F from compendium client

.sbtopts, build.sbt, modules/server/src/main/resources/application.conf, modules/server/src/main/resources/db/migration/V1__add_protocols_table.sql, modules/server/src/main/scala/higherkindness/compendium/core/CompendiumService.scala, modules/server/src/main/scala/higherkindness/compendium/db/DBService.scala, modules/server/src/main/scala/higherkindness/compendium/db/FileDBService.scala, modules/server/src/main/scala/higherkindness/compendium/db/PgDBService.scala, modules/server/src/main/scala/higherkindness/compendium/db/queries/Queries.scala, modules/server/src/main/scala/higherkindness/compendium/migrations/Migrations.scala, modules/server/src/main/scala/higherkindness/compendium/models/models.scala, modules/server/src/test/scala/higherkindness/compendium/db/DBServiceStub.scala, modules/server/src/test/scala/higherkindness/compendium/db/FileDBServiceSpec.scala, modules/server/src/test/scala/higherkindness/compendium/db/PGHelper.scala, modules/server/src/test/scala/higherkindness/compendium/db/PgDBServiceSpec.scala, modules/server/src/test/scala/higherkindness/compendium/db/QueriesSpec.scala
=> Postgres as DBService for metadata

.travis.yml, build.sbt, docker-compose.yaml
=> Use right repository in docker

modules/server/src/main/scala/higherkindness/compendium/http/RootService.scala, modules/server/src/test/scala/higherkindness/compendium/http/RootServiceSpec.scala
=> Return BadRequest if the json is incorrect

modules/common/src/main/scala/higherkindness/compendium/models/errors.scala, modules/server/src/main/scala/higherkindness/compendium/http/QueryParams.scala, modules/server/src/main/scala/higherkindness/compendium/http/RootService.scala, modules/server/src/main/scala/higherkindness/compendium/models/transformer/types.scala, modules/server/src/test/scala/higherkindness/compendium/core/CompendiumServiceStub.scala, modules/server/src/test/scala/higherkindness/compendium/http/RootServiceSpec.scala
Closes #103 
Transformation endpoint tests. I also add the missing idl name params validation.
=> Add transformation endpoint tests

NOTICE.md, README.md
This PR adds a README that highlights some of the current compendium features, also points out to the end to end example, and the SBT plugin. Feel free to modify the text, fix typos, etc.
=> Add proper README

modules/server/src/main/scala/higherkindness/compendium/core/CompendiumService.scala
Closes #102 
In this PR we are storing the resulting protocol after the transform process.
=> Storing transformed protocols

.travis.yml
=> Expose DOCKER_USER

.mergify.yml
This change has been made by @angoglez from https://mergify.io simulator.
---
<details>
<summary>Mergify commands and options</summary>
<br />
More conditions and actions can be found in the [documention](https://doc.mergify.io/).
You can also trigger Mergify actions by commenting on this pull request:
- `@Mergifyio refresh` will re-evaluate the rules
- `@Mergifyio rebase` will rebase this PR
- `@Mergifyio backports <destination>` will backport this PR on `<destination>` branch
Additionally, on Mergify [dashboard](https://dashboard.mergify.io/) you can:
- look at your merge queues
- generate the Mergify configuration with the simulator.
Finally, you can contact us on https://mergify.io/
</details>
=> Add Mergify for patch updates

.travis.yml
Now, instead of using a new stage, I use a deploy step after the docker image is built and tagged
=> Change travis configuration for docker publish

.mergify.yml, README.md
=> Mergify: Merge minors when they are approved by one collaborator

docs/docs/docs/sbt/index.md, docs/src/main/resources/microsite/data/menu.yml
- Remove unused `mdoc` to properly render the site
- Add _Sbt plugin_ section to menu
- Minor formats
=> Initial suggestions

.github/workflows/ci.yaml, .github/workflows/doc.yaml, .github/workflows/release.yaml
Build and publish microsite using GitHub Actions:
- CI / Microsite: runs `sbt docs/makeMicrosite` to check documentation on every push
- Release / Publish microsite: updates `gh-pages` branch with latest documentation on every push on `master`
=> Set up microsite

src/main/resources/compendium.yaml
Close https://github.com/higherkindness/compendium/issues/31
=> OpenAPI docs

build.sbt, src/test/scala/higherkindness/compendium/core/ProtocolUtilsSpec.scala, src/test/scala/higherkindness/compendium/storage/StorageStub.scala
=> Update cats-effect 2.1.3

.scalafmt.conf, src/main/scala/higherkindness/compendium/migrations/Migrations.scala
=> Update scalafmt-core to 2.6.0
